version: '3'

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=example
      timeout: 20s
      retries: 10
    networks:
      - recipe_api_network

  api:
    build: .
    container_name: recipe-api
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      DB_DSN: root:example@tcp(db:3306)/recipe?parseTime=true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - recipe_api_network

networks:
  recipe_api_network:
